### ISSUE TITLE
Nextclade ERR: The application panicked (crashed).

### ISSUE THREAD

**Issue by Wen1953** [nextstrain/nextclade#1138]
Hi, I'm trying to run nextclade v2.13.1 locally without an existing database and I see the next message that the application panicked.  I have follow nextclade instructions to create input files > https://docs.nextstrain.org/projects/nextclade/en/stable/user/input-files.html 
............................................................................
nextclade run --input-ref reference.fasta --input-tree final.json --input-gene-map genemap.gff --input-qc-config qc.json --input-pcr-primers primer.csv --input-virus-properties virus_properties.json --output-all=output/ sequences.fasta 
**The application panicked (crashed).**
**Message:  index out of bounds: the len is 1709 but the index is 1709**
Location: packages_rs/nextclade/src/align/gap_open.rs:23

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
**Abortado (`core' generado)**
..............................................................................
Some idea how to solve it?

**Comment by ivan-aksamentov** [comment]
@Wen1953 If I understand correctly, you have created your own dataset, including, for example, files like `genemap.gff` and `reference.fasta`.

It seems that Nextclade tries to access the array `gap_open_close` here on line 23:

https://github.com/nextstrain/nextclade/blob/c0807f5a1f4c8b44b7e8749b398157df4990ea22/packages_rs/nextclade/src/align/gap_open.rs#L23

at index `1709`, but it's length is less than that.

The `gap_open_close` is created on line 9, such that its length is equal to the length of reference sequence + 2, i.e. the length of sequence in `reference.fasta`, plus 2:

https://github.com/nextstrain/nextclade/blob/c0807f5a1f4c8b44b7e8749b398157df4990ea22/packages_rs/nextclade/src/align/gap_open.rs#L9

The array access on line 23 is happening on gene boundaries, as described by the `genemap.gff`. 

My current hypothesis is that genes in your gene map go beyond the reference sequence length. This causes out-of-bounds array access, which causes the crash. Please make sure that your gene map correctly describes the reference sequence, and all genes fit inside its range.

But it can also be an off-by-one bug in Nextclade.

If in doubt, please upload your full dataset (e.g. in a GitHub repo) so that we can investigate.

So far Nextclade datasets have been mostly created by the Nextclade team, and we try to ensure that the different files within a dataset are compatible with each other. However, because there is an increase of interest by the community in creating new datasets, we should definitely add some error handling in this part of the code and to produce a more meaningful error message. If you have time and forces, feel free to contribute an improvement. This would help other people creating Nextclade datasets.

**Comment by Wen1953** [comment]
Thanks @ivan-aksamentov . Your hypothesis was right, it was a problem with the files and the reference sequence length and not a nexclade bug. We are trying to work with some avian flu sequence even though there is not a database in nextclade. We are convinced that contribute with more databases to other pathogens will be very useful to science comunity.
