### ISSUE TITLE
ENH(web): Allow us to hide a dataset from the dataset selector

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/nextclade#1164]
We've deprecated the `sars-cov-2-no-recomb` dataset. It's still available in the index so nothing breaks for users linking to it, but we no longer update it.

However, it still shows in the dataset selector.

It would be great if we could specify in the index that a dataset should not be shown.

**Comment by ivan-aksamentov** [comment]
Would you like to add a "deprecated" flag instead? Can manifest with a yellow "deprecated" badge and the entry being greyed out for example.

**Comment by ivan-aksamentov** [comment]
We've reworked datasets since then and dataset authors can now set a "deprecated" flag in pathogen.json (as documented in the dataset curation guide). Deprecated datasets are moved the dataset to the bottom of the list and display a "deprecated" badge. The readme.md file should also help to provide context to the users of deprecated datasets.
