### ISSUE TITLE
ENH:  enlarge Visualization when more nucleotides/Codons even if mutations not fall in striclty adjacent codons but close enough to need a whole view.

### ISSUE THREAD

**Issue by FedeGueli** [nextstrain/nextclade#1272]
Especially with BA.2.86 is becoming very hard to explore additional nuc mutation in the rbd especially in the part with the 483del.
WOuld be possible when there are, to say three or more mutations in non consecutive codons but close enough to interfere  each other to have a lrger visualization?
To say: 3 nuc in a row of 5 AA hovering over the mutations i would like to see them all together not each one for each codnn ad it happens for 3+ AA deletions? 

example: 

EPI_ISL_18378395 (found by @nkrmnzr) 
![Schermata 2023-10-13 alle 01 17 50](https://github.com/nextstrain/nextclade/assets/87669813/e405318a-0828-478f-88f1-67a37a6952fe)
it has G23006A happening between N481K V483Del and A484K. Theorically it creates a Serine there at 482 (AGT due to the 483 del) but Nextclade and Gisaid don't show it. 

Having a larger visualization could help. I think @ryhisner many months ago had the same idea i dont recall if for TRS discovering or whatever.

**Comment by ivan-aksamentov** [comment]
Hi Federico @FedeGueli!

Yes, that's been on our radar for some time, but we never had enough time to work on it.

We've been also receiving conflicting requests. Some people want more info columns and less space for the sequence view, or even to completely remove it. Others are only interested in sequence view and want to remove the extra columns to give some more space for it. There's been also a pressure on us to not add any more extra columns, even if we considered the new info potentially useful. I guess it depends on individual use case and in the end the table should be configurable somehow.

As a workaroung, you can download the alignment and/or translation fasta and inspect them in alignment viewer of your choice (e.g. AliView is not bad). I realize that it's not as convenient though.

The upcoming Nextclade v3 ([here](https://master.clades.nextstrain.org/) is an early, potentially buggy preview of it) groups aa mutations that are not only immediately adjacent but also 1-codon away. This makes slightly less groups and they are slightly more compact in the sequence view. Perhaps this can help a little? But I realize it's not the final solution either.

Ideally, want a fully-featured alignment viewer, with pan & zoom, so that you can scale and scroll the view and, perhaps, if you zoom close enough even see individual nucs/aas. But it's quite challenging to implement in a web app, and, especially, embed it into the existing table rows.  So I cannot give any promises here. We are a small research lab and have to balance our time between different things.

You can help to make it happen: if you or someone you know have dev skills and time to implement this feature, consider contributing to the project - it's open source.

**Comment by FedeGueli** [comment]
Thank you very much Ivan, i ve tried the V3 and it resolves all my requests!! Thank you very much!! 
You as a little team did a huge work a a huge thanks is deserved to you. 
Without your work any fast efficient variant spotting and tracking would have been delayed a lot.
Unfortunately no coding here ! But happy to help in any other way (test, feedback, whatever) .
ah maybe variant spotters with coding skills as @aviczhl2 @over-there-is  @olias120676  could have some time to help.

Thank you very much!
