### ISSUE TITLE
linux-musl artefact gets slower rather than faster when parallelizing in contrast to gnu

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/nextclade#1338]
Not thinking much, I downloaded the v3 x86 linux-musl artefact onto our scicore cluster.

It turns out that on that cluster at least, the musl artefact does _not_ get faster when increasing the number of processes with `-j`, in contrast to the `gnu` artefact (both downloaded from here: https://github.com/nextstrain/nextclade/releases/download/3.0.0-alpha.1/nextclade-x86_64-unknown-linux-musl https://github.com/nextstrain/nextclade/releases/download/3.0.0-alpha.1/nextclade-x86_64-unknown-linux-gnu)

The musl executable still keeps the CPU busy, it just doesn't seem to do any actual work.

For `-j1` the difference between the two versions is small:
<img width="1913" alt="image" src="https://github.com/nextstrain/nextclade/assets/25161793/ad6da3d2-16c2-4f37-bd8a-f95383702f65">

For `-j10` it's huge: musl actually gets slower in real time, and consumes much more overall cpu time
<img width="1913" alt="image" src="https://github.com/nextstrain/nextclade/assets/25161793/e7f6af11-80a1-400a-9233-9a7e9c936a2c">

**Comment by corneliusroemer** [comment]
v2 binaries show the same behaviour, so this isn't a v3 problem and thus likely not something to worry about right now.

<img width="1896" alt="image" src="https://github.com/nextstrain/nextclade/assets/25161793/ccd993f3-0bc5-473b-b761-7d123808cd18">

**Comment by corneliusroemer** [comment]
Upstream discussion:
- https://github.com/rust-lang/rust/issues/70108

**Comment by ivan-aksamentov** [comment]
This is a general problem with musl. Probably nothing to do with Rust.

Adding jemalloc, mimalloc or another memory allocator for musl builds conditionally might help.

**Comment by corneliusroemer** [comment]
Do we know if anyone uses our musl builds? We could also ditch the musl build if it's a headache.

**Comment by ivan-aksamentov** [comment]
There is no headaches with musl build. It just exists and does not require any attention, other than the issue you brought up.

Users on old Linux distros, like often happens with clusters in universities and research institutions, can run only this flavor, because the GNU favor crashes if it cannot find a recent version of Linux kernel and of libc. So it might be useful for some users and I don't see any particular reason to remove it.

Documentation explains the difference between favors, and states that musl build is known to be substantially slower. I don't want to go any further than that currently - we have better things to do IMO. If there's any interest in performance improvements of musl build, then contributions are welcome.
