### ISSUE TITLE
Is there any example for handling HIV data?

### ISSUE THREAD

**Issue by liamxg** [nextstrain/nextclade#1346]
Dear @ivan-aksamentov,

Could I know if there is any example for handling HIV data to run alignment, mutation calling, clade assignment, quality checks and phylogenetic placement?

**Comment by ivan-aksamentov** [comment]
@liamxg There isn't at this time, but we experimented internally a little with it. There is a few problems to solve with regards to HIV, because it's a very diverse virus.

In Nextclade v3 it will be easier to create datasets, so you could create your own (or multiple of them). Here is a preview of how it might look like in Nextclade v3: https://github.com/nextstrain/nextclade_data/blob/master/docs/dataset-curation-guide.md
