### ISSUE TITLE
if the qc.overallStatus of  my sequences are mediocre, can we keep them for next step analysis?

### ISSUE THREAD

**Issue by liamxg** [nextstrain/nextclade#1362]
Dear @nextclade team,
if the qc.overallStatus of my sequences are bad, should we remove them for next step analysis?

**Comment by ivan-aksamentov** [comment]
Dear Liam @liamxg,

Yes, the QC overall status (derived from overall QC score) are empirical metrics which give you some idea of quality of the genome, according to the beliefs of our team. You can learn more about QC in the [documentation](https://docs.nextstrain.org/projects/nextclade/en/stable/user/algorithm/07-quality-control.html) and/or by inspecting [source code](https://github.com/nextstrain/nextclade/tree/c257a824a004f68f1ba031cecd28e970ff3a3989/packages_rs/nextclade/src/qc).

QC subsystem is configurable in the dataset (in `qc.json` file for v2 or in [`pathogen.json` file](https://github.com/nextstrain/nextclade_data/blob/609d7c6fb3d614192ccb395e547e94614591bdc8/data/nextstrain/sars-cov-2/wuhan-hu-1/orfs/pathogen.json#L53) for v3), so that you can customize it to your needs. Finally, you can implement your own metrics using Nextclade's analysis results or even using aligned sequences.

There is no absolute metric that would tell you what you "should" or "should not" do. Not in Nextclade, not anywhere else. As Cornelius mentioned, Nextclade only tries to attract attention to certain (not all) issues that it detected. The final judgement is yours, and it depends on the goals of your particular research project.
