### ISSUE TITLE
Beginners Help with Nextclade CLI

### ISSUE THREAD

**Issue by ryhisner** [nextstrain/nextclade#1416]
I'm trying to figure out how to use Nextclade CLI. I follow all the directions, but nothing ever seems to work. For example, after trying to run a fasta multiple times, the error messages indicated I needed an input dataset. So I've followed the directions to get one, but nothing works. Basically, it says to use:

nextclade dataset get [OPTIONS] --name <NAME> <--output-dir <OUTPUT_DIR>|--output-zip <OUTPUT_ZIP>>

I've tried both 

nextclade dataset get --nextstrain/sars-cov-2/wuhan-hu-1/orfs --output-dir .

nextclade dataset get --SARS-CoV-2 --output-dir .

neither of which work. It says that both nextstrain/sars-cov-2/wuhan-hu-1/orfs and SARS-CoV-2 are "unexpected arguments" even though these are the exact names listed on the input dataset list. 

I have no idea what I'm doing wrong.

**Comment by ryhisner** [comment]
Thank you for this assistance. I've gotten caught up in several other projects in the past couple of weeks, but I'm setting out this weekend to learn this in earnest. 

I printed out the Nextclade documentation and spent the last week reading it all. That, along with your advice here has been helpful. I think I've figured out the basics of how to run Nextclade and get the sort of file I want (an ndjson at the moment).  

I do have a few questions about parts of the documentation.

1. "Add multiple occurrences to increase verbosity further." I need all the help I can get, so I'd like to make Nextclade as verbose as possible. But I'm not sure what "multiple occurrences" means. Does it mean that you type in multiple v's, as in:
`-vvvvv` or maybe `-v -v -v -v`  ? How many do you have to enter for maximum verbosity?

2. Are the brackets and other symbols in documentation real or not? For example, in the section below from the Nextclade documentation, am I supposed to include the brackets, the < and > symbols, and the "..."? Or are those not real? Based on what you said in the post above, I'm guessing they're not real, but I want to be 100% sure. I don't know how to tell things that are required to be in the code from things that are there but aren't supposed to be part of the code, and there doesn't seem to me to be any possible way to tell the difference. Is there an easy way to know this?
<img width="1321" alt="image" src="https://github.com/nextstrain/nextclade/assets/33738461/6291fec4-01fb-41c9-8cd7-e3076d978cb5">

**Comment by ivan-aksamentov** [comment]
> Does it mean that you type in multiple v's, as in:
-vvvvv or maybe -v -v -v -v ? How many do you have to enter for maximum verbosity?

I think either should work. But I usually use the `-vvv` form. Note that the verbosity levels higher than `info` (with one `-v`), including `debug` and `trace` verbosity levels, are mostly only useful for developers - they print way too much technical stuff, which will just confuse you more. Note that `verbosity` only affects what's printed to the console. Output files are always the same.

> Are the brackets and other symbols in documentation real or not? 

This is a convention for denoting variables (placeholder values). The `<thing>` means required value, meaning you **have to** substitute a thing there. While `[thing]` means optional value. You don't need to enter brackets, only the value itself.

I think the convention originally comes from `man` ([1](https://stackoverflow.com/questions/67840640/what-do-square-brackets-mean-in-the-documentation), [2](https://man7.org/linux/man-pages/man1/man.1.html)) - a tool to read manual pages on Unix-like systems.

> I think I've figured out the basics of how to run Nextclade and get the sort of file I want (an ndjson at the moment)

I would not recommend JSON-based outputs, because they are unstable, meaning the format can change without notice. This is mentioned in the docs. You probably want TSV output (`--output-tsv`). It's stable and easy to open in Excel, Google Sheets or any other spreadsheet software (use "tab" as column delimiter when asked), as well as to process it let's say in a Python script (e.g. using `pandas` package) - that's what we recommend for most users.

**Comment by ryhisner** [comment]
Thank you. I have used the Nextclade Web export files a lot, so I'm familiar with those. I'm trying to get ndjson files because I want to be able to search them using Julia, which I (half) learned and was ready to start using before I realized there was something called bash that I really should've learned before I ever even tried Julia because it's impossible to do anything without bash.

**Comment by ryhisner** [comment]
Is there a way to get the GISAID accession numbers from Nextclade? I'm doing a search and the only results I can get are the sequence names, which I then have to paste one at a time into the GISAID text search in order to find and download the fastas. I'd like to be able to paste all the EPI_ISL numbers at once so I can download them easily, but I don't see them anywhere in the TSV file or the ndjson file and I'm not sure where else they would be.

**Comment by ivan-aksamentov** [comment]
> Is there a way to get the GISAID accession numbers from Nextclade?

Not sure what you mean here. Nextclade software does not deal with GISAID and does not even know what accession is, or that GISAID even exists. We don't rely on any database. The only source of data is the input files users provide - input fasta files and dataset files.

Sequence names are taken from your input fasta file and presented in the output files as is. If your fasta file does not contain accession you will not get it from Nextclade. So it's your responsibility to set the names in your input fasta such that you get desired names in the output TSV.

Or do you mean something else?

By the way, sequence names are not guaranteed to be unique - scientists often don't bother with naming their produced sequences too much and it's a bit of a chaos. So it's not always possible to deduce exact sequence just from the name.
