### ISSUE TITLE
How to get the latest Lineage- with CLI 

### ISSUE THREAD

**Issue by kiranpatil222** [nextstrain/nextclade#1449]
Hi,

If there is a new Variant and lineages ,, CLI . nextclade.tsv is not reporting even after updating the version,
How do i get latest updated Variants Lineages

**Comment by ivan-aksamentov** [comment]
Hi @kiranpatil222, note that the information on clades and lineages comes from [datasets](https://docs.nextstrain.org/projects/nextclade/en/stable/user/datasets.html). Make sure you are using the latest dataset.

In order for me to be able to help:

 - Which dataset are you using? (Nextclade currently provides [5 SARS-CoV-2 datasets](https://github.com/nextstrain/nextclade_data/tree/master/data_output/nextstrain/sars-cov-2))
 - Have you downloaded the latest version of the dataset?
 - Which version of Nextclade CLI are you using?
 - How do you run Nextclade CLI (provide full commands)?
 - Which variants and lineages are you missing?

**Comment by kiranpatil222** [comment]
Hi Ivan, Thank you for the clarification dataset was old, so it was not updating Lineages,
I presumed conda update nextclade will update with dataset.
Just one more question how do we keep track of latest dataset updates.?
or How often it changes

**Comment by ivan-aksamentov** [comment]
@kiranpatil222 Datasets are small (a few megabytes at most), so we recommend (in the documentation) that most users download their datasets fresh every time they start a new session, e.g. when you come to the lab in the morning and want to analyze a batch of new data, or if you are running nextclade as a part of daily automated workflow, then download the dataset in your workflow just before starting nextclade run, i.e. there is no reason to persist the dataset.

If you don't need dataset files on your computer, you can also try `nextclade run` command with `--dataset-name` argument instead of `--input-dataset`. In this case Nextclade will download a fresh dataset in-memory and will run the analysis immediately with it, so that the separate `nextclade dataset get` command is not needed.

You can track new dataset releases on GitHub Releases page of our data repository:
https://github.com/nextstrain/nextclade_data/releases
You can subscribe to notifications on GitHub by selecting "Watch" -> "Custom" -> "Releases" on the top panel of that page. You can configure GitHub to only send notification within the app (https://github.com/notifications) or to also send emails.

Finally, you can use `nextclade dataset list` command (optionally with `--json` flag) to keep track of the list of versions for each dataset, and react when the list changes.

**Comment by ivan-aksamentov** [comment]
I will close the issue for now. Please comment or create a new one if there's still outstanding problems.
