### ISSUE TITLE
Possible off-by-one error in json output

### ISSUE THREAD

**Issue by marcmtk** [nextstrain/nextclade#259]
Dear maintainers

The JSON output from https://clades.nextstrain.org/ seems to have a one nucleotide/codon difference for csv/tsv compared to json:

Steps to reproduce:
Upload [target.txt](https://github.com/nextstrain/nextclade/files/5501549/target.txt)
Export to json and csv
Compare

JSON (pertinent area):

```
{
        "pos": 22919,
        "refNuc": "A",
        "queryNuc": "T",
        "aaSubstitutions": [
          {
            "refAA": "Y",
            "queryAA": "F",
            "codon": 452,
            "gene": "S"
          }
        ],
        "pcrPrimersChanged": []
      }
```

csv:
```
seqName;substitutions;totalMutations;aminoacidChanges;totalAminoacidChanges;insertions;totalInsertions;deletions;totalGaps;missing;totalMissing;nonACGTNs;totalNonACGTNs;alignmentStart;alignmentEnd;alignmentScore;pcrPrimerChanges;totalPcrPrimerChanges;clade;qc.seqName;qc.privateMutations.score;qc.privateMutations.total;qc.privateMutations.excess;qc.privateMutations.cutoff;qc.privateMutations.status;qc.missingData.score;qc.missingData.totalMissing;qc.missingData.missingDataThreshold;qc.missingData.status;qc.snpClusters.score;qc.snpClusters.totalSNPs;qc.snpClusters.clusteredSNPs;qc.snpClusters.status;qc.mixedSites.score;qc.mixedSites.totalMixedSites;qc.mixedSites.mixedSitesThreshold;qc.mixedSites.status;qc.overallScore;qc.overallStatus
hCoV-19/Denmark/DCGC-2965/2020|EPI_ISL_616727|2020-08-24;A22920T,A23403G,A23636G,G25249T;4;S:Y453F,S:D614G,S:I692V,S:M1229I;4;;0;21766-21772;6;;0;;0;21623;25450;11444;;0;20A;hCoV-19/Denmark/DCGC-2965/2020|EPI_ISL_616727|2020-08-24;12.5;3;1;8;good;0;0;3000;good;0;0;;good;0;0;10;good;1.5625;good
```

Kind regards and thanks for your hard work :)
Marc

**Comment by ivan-aksamentov** [comment]
Hi @marcmtk, thanks for reaching out!

This is by design currently. The JSON export is an exact snapshot of the internal data structure (basically a `JSON.stringify(state)`, followed by writing to a file). And because our algorithms operate on 0-based arrays and strings, this data structure also has 0-based positions.

By contrast CSV, TSV exports and what you see in the web app are all different visual representations (rendering) of this data structure, and during this rendering we add 1 to positions, to align with the usual conventions in the community.

I originally thought that this would prevent from complex processing of this data structure and facilitate import and persistence of results, when we have these features.

But I see how this can be confusing. I can think of the following steps we can take:

 - improve documentation, to make sure users understand that the JSON export is 0-based (downside: users  not always read the documentation)

 - or make JSON output 1-based (breaking change; additional work; error prone - we may forget to add 1 to the new things we introduce; import and persistence of results will be not as straightforward)

From user's perspective, what do you think will be the best solution here? It is fine to keep it 0-based?

cc @rneher

**Comment by marcmtk** [comment]
I think it is perfectly fine to keep it 0-based.

Ideally I'd like some sort of hint in the JSON file, but as I understand it
JSON and comments don't play nice.

A brief mention somewhere in the documentation would be plenty helpful,
while also preserving your resources for bigger issues 😊

**Comment by corneliusroemer** [comment]
I've added a brief explanation of 0- vs 1-indexing to the docs.
