### ISSUE TITLE
0.10.1 freezing in Firefox 84.0 with 'too much recursion'

### ISSUE THREAD

**Issue by DrYak** [nextstrain/nextclade#289]
When I tried uploading a fasta file with ~500 sequences (the unfiltered sequences from the next batch that should be uploaded into GISAID soon-ish).

Under Firefox 84.0, the progess bar freezes and the JavaScript console reports:
 - InternalError: too much recursion, NextJS 21, fsaSagaFromParams.ts:31:14

Same file works under Chromium 87.0.4280.88 

I can provide the file over PolyBox or SwitchDrive if needed.

![Screenshot_20210103_150101](https://user-images.githubusercontent.com/11413679/103480692-f93f9a80-4dd5-11eb-9ccf-0c881589893c.png)

**Comment by ivan-aksamentov** [comment]
Hi @DrYak, thanks for the report.

Just to clarify, does it eventually unfreeze or is it gone forever?
There's been reports that adblockers break Nextclade in various funny ways (I see at least uBlock on your screenshot).

We don't have ads or tracking, but do a lot of heavy JavaScript for sequence processing, and addons may interfere with that. Not mentioning that they slow things down significantly. Any chance you can disable them or run in a separate, addon-free private instance of Firefox?

Otherwise it might be something we could try fixing. I will attempt to contact you through email with regards to file sharing. 

We are also working towards reimplementing the algorithms in C++, which should make Nextclade much snappier and more robust. But it's not there yet.

Meanwhile, if that's a blocking issue, as a workaround you could try either of:
 - a Choromium-based browser
 - [CLI version](https://github.com/nextstrain/nextclade/blob/master/packages/cli/README.md)
 - to bisect the sequence file, find the problematic sequence and exclude it

Thanks again for the reaching out!

**Comment by DrYak** [comment]
After a minor update on my distro this morning (didn't check exactly what exactly got updated :-/ ), the newest version now merely pauses for a second (or so) and resumes and successfully process the files. 

(Including multiple "internet condom" type of plugins: NoScript, uBlock, PrivacyBadger, DecentralEyes)

Looking forward to the C++ / WASM version!

**Comment by ivan-aksamentov** [comment]
@DrYak Thanks for the update Ivan!

I will keep the issue open until we definitely address this. Here are also some more thoughts for other users if they also stumble upon this issue:

For batches of 500 sequences, Nextclade, even in CLI mode, consumes awfully lot of memory - up to 8 Gigabytes and even more depending on quality of sequences. So in the end its related to the amount of system memory available, and how Firefox manages JavaScript heap memory (i.e. garbage collection). In principle, Chromium is not invincible either, and one could crash it given a sufficiently large batch too.

In this case, closing browser tabs and other applications *might* help, by freeing up some RAM. Same idea with for splitting large batches into multiple smaller ones (this is what we do in our internal pipelines). Otherwise, the CLI version in a cloud or on a cluster is also an option. There is also ongoing work to render exported JSON from previous results in the app or from CLI.

Initially we did not expect Nextclade to ever need to reach this scale of compute (like it happened for many other tools, given the uncontrolled pandemic and the explosion of available sequencing data amounts we observe), and the JS implementation definitely shows its limits. We are hoping that the explicit memory management of C++ can help to alleviate this and some other problems.

**Comment by rneher** [comment]
The c++ wasm version is here!
