### ISSUE TITLE
inconsistent columns in web and cli

### ISSUE THREAD

**Issue by tolot27** [nextstrain/nextclade#312]
The web-exported and cli-generated output files contain different number of columns/fields. Version in use: 0.12.0.

The web-exported files contain `qc.seqName` and `nearestTreeNodeId`, whereas the cli-generated files do not.

The redundant column `qc.seqName` has been removed from CSV and TSV results with release 0.8.0, according to changelog. But the currently running web version still exports this column.

Why is `nearestTreeNodeId` [removed](https://github.com/nextstrain/nextclade/blob/8767611a95b308ff33d26c73ff536fd999615e10/packages/web/src/cli/run.ts#L66-L68) from the cli-exported files and still present in the web-exported files? We use this column to group the results in our dynmaically generated reports.

**Comment by ivan-aksamentov** [comment]
Hi Mathias @tolot27,

Thanks for the report and sorry for the troubles.

The short answer is that presence of these in the outputs is a bug:

> The web-exported files contain qc.seqName and nearestTreeNodeId

They were never meant to be there.

`nearestTreeNodeId` is a relatively random number which is only used internally and was not meant to be exposed to end users in any form. It is a workaround for objects not preserving reference equality when crossing webworker boundaries, so we needed to keep a handle in order to find the node. They are added to nodes and results before tree construction and are (meant to be) removed after it is done.

> group the results in our dynmaically generated reports

I am not sure what it means, but "the most correct" solution would be to ignore the column and to not use it for anything. Unless you found a specific use for it.

In any case, contributions are super welcome! :pray:
