### ISSUE TITLE
Is there a way to trigger an analysis by curl command or any API?

### ISSUE THREAD

**Issue by xzhub** [nextstrain/nextclade#338]
I'd like to know if there is a way to start an analysis on a given sequence so that we can redirect some queries from my other web site to my nextclade local installation. Thanks in advance!

Also, I'd like to know if there is any plan to support multiple fasta files uploading? Currently, users can only upload one multi-entry fasta file for multi sequences analysis.

**Comment by ivan-aksamentov** [comment]
Hi @xzhub,

No, Nextclade is a static application, performs all computations in the browser, and there is no official standalone API server to make a request to. 


However, Nextclade client supports URL query parameters, which has the same names as Nextclade CLI command-line arguments:
https://github.com/nextstrain/nextclade/blob/7e031ac27f5431321d6c06cf6415b79bd47910b7/packages/web/src/io/fetchInputsAndRunMaybe.ts#L19-L21

You can think of it as a GET request to an API, but it will reply with HTML, because that's all static web servers can do.


The algorithm code is relatively independent of the UI code, so it would not be to hard to build an API server, if you really want to. However we don't plan to implement or maintain it. You can use Nextclade CLI as an insiparion:

This directory contains README for Nextclade CLI:
https://github.com/nextstrain/nextclade/tree/7e031ac27f5431321d6c06cf6415b79bd47910b7/packages/cli

And this directory contains Nextclade CLI source code:
https://github.com/nextstrain/nextclade/tree/7e031ac27f5431321d6c06cf6415b79bd47910b7/packages/web/src/cli
As you see it just imports and runs things from `io` and `algorithms` directories. You can do the same in your Node.js server.

Related: https://github.com/nextstrain/nextclade/issues/205 https://github.com/nextstrain/nextclade/pull/203 https://github.com/nextstrain/nextclade/pull/247

**Comment by ivan-aksamentov** [comment]
>  is any plan to support multiple fasta files uploading?

No we don't plan that. However, we are open for discussion. Feel free to open a separate issue. Describe well why you think this is a good feature and what are the use cases, and someone might jump in and actually implement it.

**Comment by xzhub** [comment]
> Hi @xzhub,
> 
> No, Nextclade is a static application, performs all computations in the browser, and there is no official standalone API server to make a request to.
> 
> However, Nextclade client supports URL query parameters, which has the same names as Nextclade CLI command-line arguments:
> https://github.com/nextstrain/nextclade/blob/7e031ac27f5431321d6c06cf6415b79bd47910b7/packages/web/src/io/fetchInputsAndRunMaybe.ts#L19-L21
> 
> For example:
> 
> ```
> https://clades.nextstrain.org/?input-fasta=https://raw.githubusercontent.com/nextstrain/nextclade/8767611a95b308ff33d26c73ff536fd999615e10/packages/web/src/algorithms/defaults/sars-cov-2/sequenceData.fasta
> ```
> 
> Several options:
> 
> * You can think of it as a GET request to an API, but it will reply with HTML, because that's all static web servers can do. So you will have to render that somehow.
> * With these URL params, you can also link out from your website to `clades.nextstrain.org` or to your own instance.
> * You can render the URL in an `iframe`.
> * Finally, you can try and import Nextclade React components to your web app and use them as you wish.
> 
> Regarding server, the algorithm code is relatively independent of the UI code, so it would not be to hard to build an API server, if you really want to. However we don't plan to implement or maintain it. You can use Nextclade CLI as an insiparion:
> 
> This directory contains README for Nextclade CLI:
> https://github.com/nextstrain/nextclade/tree/7e031ac27f5431321d6c06cf6415b79bd47910b7/packages/cli
> 
> And this directory contains Nextclade CLI source code:
> https://github.com/nextstrain/nextclade/tree/7e031ac27f5431321d6c06cf6415b79bd47910b7/packages/web/src/cli
> As you see it just imports and runs things from `io` and `algorithms` directories. You can do the same in your Node.js server.
> 
> Related: #205 #203 #247

This is exactly what I am looking for. Thanks a lot!

**Comment by xzhub** [comment]
> > is any plan to support multiple fasta files uploading?
> 
> No we don't plan that. However, we are open for discussion. Feel free to open a separate issue. Describe well why you think this is a good feature and what are the use cases, and someone might jump in and actually implement it.

opened another feature request on this #342

**Comment by chaoran-chen** [comment]
Hi @ivan-aksamentov, the current query param-based solution sounds amazing!

But is https://clades.nextstrain.org/?input-fasta=https://raw.githubusercontent.com/nextstrain/nextclade/8767611a95b308ff33d26c73ff536fd999615e10/packages/web/src/algorithms/defaults/sars-cov-2/sequenceData.fasta supposed to work? I tried Chrome (with disabled ad-blocker), Firefox (plain installation, without any manually installed plugins), and Edge (also a plain installation) and always get an "Error: Network connection failed".

In Chrome, I see the following message in the console:

![image](https://user-images.githubusercontent.com/18666552/108507574-d18b8f80-72ba-11eb-8050-3aa72c1d8d95.png)


Thank you very much!

**Comment by ivan-aksamentov** [comment]
@chaoran-chen

Oh, that's a bug. This might be related to the recent changes to Content Security Policy I've made.

Thanks for reporting! I will look into this right now.

**Comment by ivan-aksamentov** [comment]
@chaoran-chen Okay, I hopefully fixed the problem in https://github.com/nextstrain/nextclade/pull/359 and it should be up in a few moments.

Could you please check it on your side? 

Sorry for the troubles.

**Comment by chaoran-chen** [comment]
Yes, it works! Thanks for the very quick fix! (This is going to be a feature that I will use a lot :))

**Comment by ivan-aksamentov** [comment]
Glad it worked!

I will close this issue as resolved, but don't hesitate to comment or to open another issue of you have questions, ideas or problems.

We are always happy to receive code contributions too!
