### ISSUE TITLE
Can i use nextclade to analysis other viruses not only SARS-CoV-2?

### ISSUE THREAD

**Issue by 544728460** [nextstrain/nextclade#409]
Nextclade is very helpful for me to analysis the clades, mutations for my local SARS-CoV-2 sequences. But if nextclade can be developed to analysis other viruses, it will be much better!

The hypothetical situation can be this:

I have a number of some kind of virus genomes which belong to the same species (maybe not coronavirus) and only several mutations among these sequences exist. I also select one of these sequence as reference and some vital positions on the reference as markers to assign clades. Then i want to proceed clade assignment, mutation calling, and sequence quality checks for these sequences using nextclade.

Can any improvement be made on this? Thanks a lot!

**Comment by davidcroll** [comment]
Hiya,

yes, you can - but you must provide your own reference sequence, clade designations/definitions and so on. On https://clades.nextstrain.org/, select "Advanced mode", and proceed from there.

Built-in support for other pathogens than SARS-CoV-2 is something we plan for the future.

Best regards, David

**Comment by 544728460** [comment]
Thanks David. 

I choosed the "Advanced mode" but can not find a place to provide my own reference sequence and clade designations/definitions. One more question, can I proceed from Nextclade CLI as a command-line tool by providing my own reference sequence and clade designations/definitions？
![image](https://user-images.githubusercontent.com/50523037/118094076-dc107d80-b400-11eb-8927-3d2a10c72e02.png)

Sincerely, Herry

**Comment by ivan-aksamentov** [comment]
Hi Herry @544728460,

All clade information is taken from the reference tree nowadays, Nextclade does not require clade definitions.

As you see in your screenshot, there are 6 input files that Nextclade needs in order to function:

 - input sequences
 - reference tree
 - root (reference) sequence
 - quality control parameters
 - gene map (genome annotations)
 - PCR primers

Nextclade Web and Nextclade CLI have defaults built-in for SARS-CoV-2 for 5 of them (all except the first one, the input sequences, of course). The gene map, if omitted, will be taken from the reference tree file, and PCR primers can be just empty for the time being, but you will need, the tree, root sequence and QC params for your new virus.

You can learn how to pass these files to Nextclade CLI by typing `nextclade --help` in your terminal (assuming Nextclade CLI is installed).

We are also having a new CLI implementation in alpha testing stage. It is not announced yet. You can learn about changes on [Releases page](https://github.com/nextstrain/nextclade/releases) (scroll down to `1.0.0-alpha.1`, which is the first release of the new version).

We have some of the data for some of the viruses for the new Nextalign and Nextclade implementations in [`data/`](https://github.com/nextstrain/nextclade/tree/master/data) directory of the repo.

Other team members were able to run the analysis on flu virus. But it's still work in progress. 

This augur profile is used to build the SARS-CoV-2 tree. You might use it as a starting point and might adapt it for your needs. Otherwise see [Nextstrain docs](https://docs.nextstrain.org/en/latest/) on how to build your own trees.

We will be glad to hear more about your use case and experience if you decide to dive into this. We are also grateful for any contributions - in form of ideas, discussions, bug reports, data and code.

The progress is tracked at https://github.com/nextstrain/nextclade/issues/213

**Comment by 544728460** [comment]
Hi David,

Thanks for your kindly answers. There is still one question I want to ask you. If I only want to get these columns "seqName", "substitutions", "deletions", "insertions", "aaSubstitutions" and don not care what the other columns are for my new designated reference and its annotation. Can i use files and the command like this:

command:
nextclade -j 64 -i test.fasta --input-root-seq MW059036.1.fasta --input-gene-map geneMap.json -t output.tsv

The involved files are attached.

It seems something is wrong although I checked the number of start positions and end positions for every CDS in geneMap.json finding no error.

The error information is as follows:

$ nextclade -j 64 -i test.fasta --input-root-seq MW059036.1.fasta --input-gene-map geneMap.json -t output.tsv
ErrorGeneInvalidRange: GeneMap: in gene "genome_annotations": expected gene length to be divisible by 3, but got NaN
    at /opt/miniconda3/envs/nextstrain/lib/node_modules/@neherlab/nextclade/dist/nextclade.js:1485:7345
    at Array.map (<anonymous>)
    at convertGeneMap (/opt/miniconda3/envs/nextstrain/lib/node_modules/@neherlab/nextclade/dist/nextclade.js:1485:6659)
    at _callee5$ (/opt/miniconda3/envs/nextstrain/lib/node_modules/@neherlab/nextclade/dist/nextclade.js:12:19017)
    at tryCatch (/opt/miniconda3/envs/nextstrain/lib/node_modules/@neherlab/nextclade/dist/nextclade.js:419:1007)
    at Generator.invoke [as _invoke] (/opt/miniconda3/envs/nextstrain/lib/node_modules/@neherlab/nextclade/dist/nextclade.js:419:4958)
    at Generator.next (/opt/miniconda3/envs/nextstrain/lib/node_modules/@neherlab/nextclade/dist/nextclade.js:419:2146)
    at asyncGeneratorStep (/opt/miniconda3/envs/nextstrain/lib/node_modules/@neherlab/nextclade/dist/nextclade.js:424:275)
    at _next (/opt/miniconda3/envs/nextstrain/lib/node_modules/@neherlab/nextclade/dist/nextclade.js:424:586)

Do you know what is wrong with my command or files?
[Uploading nextclade_test.zip…]()

**Comment by ivan-aksamentov** [comment]
Hi Heryy @544728460 ,

This would probably not make sense, because it will try to use the tree from SARS-CoV-2. What virus you are studying?

Regarding the error, the gene map file seems to be incorrect. There is `genome_annotations` field where the gene name is expected to be, and Nextclade tries to find for gene data for the gene "genome_annotations". You probably need to move the actual genes one level up.

I cannot download your files. The link just points to this issue. I think you need to wait file to upload fully before posting.

**Comment by 544728460** [comment]
Hi David,

Sorry for my  carelessness. I will upload the files again. 

I am focusing on SARS-CoV-2 now and I have some local virus genome sequences for which I want to study the mutations compared to the different references from both early phase and latest phase. What's more, I maybe try the same method on other coronaviruses such as MERS, SADS and so forth. So the outcome from nextclade will make it more convenient for me if I can choose the reference sequence and annotation even clades independently.

Considering the error mentioned before, can i steer clear of the tree file only providing the reference sequence and annotation files as parameter files since it is an optional parameter informed by help information? Or could u offer me an example of the tree file with correct format because I can not find the template tree file on  https://nextstrain.org/docs/bioinformatics/d
[nextclade_test.zip](https://github.com/nextstrain/nextclade/files/6497913/nextclade_test.zip)
ata-formats

**Comment by rneher** [comment]
The tree you need is the output of `augur export`, the endpoint of the nextstrain pipeline. In principle you can use nextstrain for any virus with a close enough reference genome and a tree of closely related sequences. We will hopefully support other viruses by default soon.

**Comment by ivan-aksamentov** [comment]
For future readers:

This has been implemented in a for of Nextclade Datasets. Each dataset is specific to a particular pathogen, or a variation of it. As of time of writing, we have default datasets for SARS-CoV-2 and 4 different Flu viruses, with plans to add more. Users can create and use their own datasets.

Please refer to the documentation: https://docs.nextstrain.org/projects/nextclade

If there are remaining questions, feel free to:
 - submit a new issue: https://github.com/nextstrain/nextclade/issues/new/choose
 - join the discussion forum: https://discussion.nextstrain.org/
