### ISSUE TITLE
Add more specific error messages to help debugging

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/nextclade#491]
When I include an invalid nucleotide in the root sequence, all I get is a fairly non-descriptive error message:

```
[ERROR] Nextclade: Error: Invalid nucleotide: "E"
```

It'd be helpful for users if the error message included the file (root seq) in which the invalid nucleotide was found, similar to how the same error in a sample sequence is reported:
```
[ WARN] Nextclade: Warning: In sequence "MK630463": Invalid nucleotide: "E". Note that this sequence will be excluded from results.
```

**Comment by ivan-aksamentov** [comment]
Error messages have been generally improved since Nextclade v2 thanks to the fantastic Rust error handling and [`eyre` crate](https://github.com/yaahc/eyre).

We no longer emit this particular error. Instead we filter out unckown nuc letters. But if we did, it would be emitted in the form of the following warning:

```
When processing sequence #0 'A/B/C': Unknown nucleotide: E. Note that this sequence will not be included in the results
```

I am going to close this issue. But let's report, review and improve the remaining issues in the error messages on individual basis.

**Comment by ivan-aksamentov** [comment]
Actually I completely misread the issue.

The better errors for ref sequence is implemented in https://github.com/nextstrain/nextclade/pull/1098
