### ISSUE TITLE
Integrating Nextclade command line within Nextstrain

### ISSUE THREAD

**Issue by mabvakureb** [nextstrain/nextclade#499]
Hello, Is it possible to integrate Nextclade command line within Nextstrain. We could update Nextstrain which would also install/ update Nextclade and Nextalign?

**Comment by corneliusroemer** [comment]
Which of the many Nextstrain tools (Augur, Auspice, Nextstrain CLI,...) would you like Nextclade to be integrated in?

What's the motivation behind your request? Do you have difficulties installing Nextclade? How do you currently install Nextclade/Nextalign? How do you install "Nextstrain" (see above for the different tools that you could mean by this).

**Comment by mabvakureb** [comment]
Hi @corneliusroemer, I used make to install on ubuntu. 

I downloaded the one shown in the image below and couldn't get it working. So I ended up using make for install and it works well. But I would like to quickly update it as updates come out, and being integrated within Nextstrain augur we can update all tools from Nextstrain.org at once using conda for example, which I used in my case to install nextstrain. I could run an update command using conda for nextstrain and all the tools will be updated at the same time with ease. 

![image](https://user-images.githubusercontent.com/73554931/129415607-05381360-5a78-42f5-8aba-000cc05ee487.png)

**Comment by rneher** [comment]
Hi @mabvakureb 
I guess we could add NextClade to the conda environment of nextstrain. NextAlign is already in there. But please let us know what didn't work with the binary you downloaded. This should have worked on Ubuntu. 

best,
richard

**Comment by mabvakureb** [comment]
Thank you @rneher. It was a silly error. The binary works fine it just needed the './nextclade --h' in the beginning rather than 'nextclade --h'

**Comment by ivan-aksamentov** [comment]
It seems like the issue was resolved.

We recommend to download a fresh version periodically, or before every run of the automated workflow.  There are [code snippets](https://docs.nextstrain.org/projects/nextclade/en/stable/user/nextclade-cli.html#download-from-command-line) in the docs that can help. Additionally, the packaging is discussed in #357 #422. There is an unofficial community-maintained conda package.

I will close this for now, but please comment or open a new issue if there are unresolved problems.
