### ISSUE TITLE
X-axis issues with Date

### ISSUE THREAD

**Issue by ShawnSimp** [nextstrain/nextclade#542]
I'm attempting to change the x-axis on the auspice tree viewer to show the date. I have change the distance measure parameter within both the input tree.json & the output auspice json to "num_date". This resulted in the axis legend changing to date but only one point appears on the tree. How can get the tree to show chronological date with my date similarly to the tree presented here:https://nextstrain.org/ncov/gisaid/global

thank you for any possible assistance.

**Comment by ivan-aksamentov** [comment]
Hi @ShawnSimp,

To better understand the issue, could you please provide an example tree json file that allows to reproduce the problem? Have you modified Nextclade's code or are you using clades.nextstrain.org?

**Comment by rneher** [comment]
@ShawnSimp In order to show a time scaled phylogeny, dates need to be inferred for all internal nodes. this is usually done in the `refine` step of the nextstrain pipeline. These inferences are not done by default for the trees we use in Nextclade because the primary purpose is representing genetic diversity of the virus rather than an epidemiological analysis. 

Once you have a tree with inferred dates of ancestral nodes, you should be able to view it in auspice.us

**Comment by ShawnSimp** [comment]
@rneher  Okay thank you for the clarity, I will do that now.
