### ISSUE TITLE
Missing tab/semicolon before error column in --output-tsv and --output-csv 

### ISSUE THREAD

**Issue by RaSieb** [nextstrain/nextclade#560]
**Current Behavior**  
The `.tsv` and `.csv` output files lack a delimiter before the `error` column when there are no errors in the analysed data.

**Expected behavior**  
There should be a delimiter before an empty "cell"

**How to reproduce**  
Steps to reproduce the current behavior:  
1. Run `nextclade run --input-dataset dataset/sars-cov-2/ --input-fasta dataset/sars-cov-2/reference.fasta --output-csv tmp.csv`   
3. tail `tmp.csv` 
4. note the missing `;` after "good". 
5. The same behaviour is observed for the `--output-tsv` option.

**Possible solution**  
Add the delimiter to the data even if there are no errors. 

**Your environment: if running Nextstrain locally**  
 - Operating system:   linux
 - CLI version 1.4.0

**Comment by ivan-aksamentov** [comment]
Hi @RaSieb,

Thanks for the report! I can confirm your findings and that it is a bug in Nextclade. I will investigate ASAP.

**Comment by ivan-aksamentov** [comment]
@RaSieb I believe that this was fixed in #562. I released the fix in Nextclade Web 1.7.1 (it's already online) and in Nnxtclade CLI [1.4.1](https://github.com/nextstrain/nextclade/releases/tag/1.4.1). If you have a second, I appreciate if you could double check that the problem is fixed and report back.
