### ISSUE TITLE
Failure to align to gene when sequence has single nt deletion in first 251nt of gene

### ISSUE THREAD

**Issue by sureman** [nextstrain/nextclade#594]
First let me thank you for providing your tools to the community.  They are invaluable to us!

We recently re-ran some sequences through the latest version of Nextclade CLI 1.4 (latest web version as well) that were originally run in version 0.14.4.  We noticed that a few sequences were not aligned to Spike and giving the "Unable to align: no seed matches" message.  A few Spike mutations had previously been called with version 0.14.4 and when we dug into the issue, we found that these particular sequences had an insertion in the beginning of Spike.  Using the reference MN908947 sequence, we introduced artificial single indels and found that any indel from MN908947.3:21563-21814 (first 251 NT of Spike) caused the otherwise wildtype Spike not to be aligned.  We found this to be the case with other genes that we tested as well in the intervals seen below:

 M -> MN908947.3:26523-26605
 N -> MN908947.3:28274-28400
 ORF1a -> MN908947.3:266-505
 ORF1b -> MN908947.3:13468-13719
 ORF3a -> MN908947.3:25393-25488
 ORF7a -> MN908947.3:27394-27459
 ORF8 -> MN908947.3:27894-27959
 S -> MN908947.3:21563-21814

Attached is a file with 2 sequences for each gene listed where we introduced a single deletion at the end of this interval and following the interval.   The sequences are otherwise identical to MN908947.3.

[MN908947_artificialDeletions.txt](https://github.com/nextstrain/nextclade/files/7445094/MN908947_artificialDeletions.txt)

**Comment by corneliusroemer** [comment]
Thank you for this report. I can reproduce the behaviour.

This seems to be a bug related to our new frame shift feature, introduced in version 1.4.0 about a month ago. Until then, all uncompensated frameshifting deletions would have caused the gene to not be translated causing this warning message. Only since version 1.4.0 do you get genes output in these cases. You can have a look at a description of the feature here: https://github.com/nextstrain/nextclade/blob/639a10a126f3a3a1acc862ef9a498ffa5cec8465/CHANGELOG.md#nextclade-web-170-nextclade-cli-140-nextalign-cli-140-2021-09-30

What happened before version 1 I can't say since I didn't work on Nextclade back then. @rneher or @ivan-aksamentov have to jump in there.

So what seems to happen here is that the new frameshift feature makes the gene fail if the frameshift happens within the first say 250nt of the gene and is not soon compensated. I'm not sure whether this is expected behaviour or not. Richard or Ivan will be able to tell.

![image](https://user-images.githubusercontent.com/25161793/139511896-408b8c84-767f-4d2e-b027-c2ed19c4bd80.png)

**Comment by ivan-aksamentov** [comment]
Hi Brad @sureman,

Thanks for the detailed report and fantastic tests! We will investigate this.

**Comment by rneher** [comment]
Thanks for the detailed report. The alignment in nextclade works by first producing a rough alignment via matched seeds, followed by Smith-Waterman alignment. If the frameshift is too early in a sequence, there isn't enough alignable amino acid sequence to produce reliable seed matches (we currently tile the sequence with a few seeds and require some minimal number of matches). The frameshifted part of the sequence will not match. if the remainder is too short processing of the gene is aborted. We could/should catch this and refine the seed matching, but this behavior is expected given the current implementation.

**Comment by sureman** [comment]
Thank you for looking into this.  Would it be possible to add the resulting error message to the error column of the "--output-tsv" file of the CLI so that it is more directly noticeable along side of the main results?

**Comment by ivan-aksamentov** [comment]
@sureman Just a quick update on this issue: we improved alignment of peptides and it was released in Nextclade CLI 1.5.0 and Nextclade Web 1.8.0. 

See https://github.com/nextstrain/nextclade/pull/613 for more details.
