### ISSUE TITLE
Do not start more threads than there are sequences

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/nextclade#654]
Even if I just input 1 single sequence, Nextclade web starts as many threads as it can, in my case 8.

This is wasteful. Wouldn't it be possible to create threads as the fasta is parsed so that at most 1 thread per sequence is created?

![image](https://user-images.githubusercontent.com/25161793/146420573-c34e6c34-b732-4e36-8ec2-54ff390aa845.png)

**Comment by ivan-aksamentov** [comment]
Why? They are initialized concurrently, so the time is the same. And if threads are unused after initialization, they consume almost no resources.

In any case, that would be difficult to implement. These are not threads really, I just wrote "threads" and now "webworkers" in hope that it's better understood. Browsers have no threads currently. And due to how the current webworker pool library is implemented it is not possible. So brand new implementation would be required.

Also, given 8 threads and slightly more than 8 sequences, let's say 12, with sequential initialization, you'd wait 8x the current time only to initialize things (i.e. initialization will be performed sequentially).

I plan to try other optimizations to speedup the init process though, just never had time so far, due to higher priority tasks.

**Comment by corneliusroemer** [comment]
Alright :)

So I guess the time isn't really spent on setting up threads but on parsing the tree? Maybe adding that to the loading message would make more transparent what's going on.
