### ISSUE TITLE
Large recurring frameshifts in Spike (possibly due to faulty library)

### ISSUE THREAD

**Issue by shepp-hub** [nextstrain/nextclade#660]
In a recent SARS-CoV-2 sequencing library, nextclade detected recurring frameshift mutations affecting the S:142-1274 range. 
This happened for 113/136 of the samples, regardless of apparent sequencing quality, depth and so fourth.
We are still trying to determine the source of the problem, and we would like to rule out nextclade as a possible culprit.
[Please see this gist](https://gist.github.com/shepp-hub/1654030d82da1ef069883558992d6a96) with two sequences, one with the frameshift and the other without it.

Thanks

**Comment by corneliusroemer** [comment]
I have hand aligned to check and yes, the frame shifted sequence shows a frame shift at 21987, because there's a single nt deletion.
![image](https://user-images.githubusercontent.com/25161793/147271320-114cf03c-7f34-4fc9-9f29-8d32fcba6960.png)

The frame shift is large (142-1274) because it's not compensated.

You should either call the whole triplet 21987-21989 a deletion or none at all.

If you're using Artic primers, they are known to have an issue at that site, could be the explanation.

In any case, this is not a Nextclade bug.

**Comment by shepp-hub** [comment]
Hi @corneliusroemer,
Nextclade bug or not, your comment was very helpful. Thanks.
