### ISSUE TITLE
Report mutations within a frame shift

### ISSUE THREAD

**Issue by MarieLataretu** [nextstrain/nextclade#694]
Hi there,

in our recent Omicron samples (21K aka BA.1) we found a few with a weird number of spike mutations, caused by a 5 nt deletion that introduces a frameshift while reads support a 6 nt deletion, see [here](https://github.com/artic-network/fieldbioinformatics/issues/100 ).

`nextclade` only reports the frameshift, but not the mutations that appear in this region.
We see the frameshift S:70-1274, missing out aaMutations on the spike from S:70 on. It would be nice to see them anyway!

(Or I'm missing a parameter to do so :) )

**Comment by corneliusroemer** [comment]
Hi @MarieLataretu, aa mutations within a frame shift is not something Nextclade/align supports at the moment.

There's been a bit of discussion about this already when the frame shift feature was introduced: #561 

I'll close this as a duplicate (I edited the title of the duplicate to be more findable). It's worth noting that while you don't get amino acid mutations in frame shifted regions, you still have the nucleotide alignment. Since a sequence with this large a frame shift is biologically unfeasible, it's most important that the pipeline that produces this frame shift gets fixed. Once that's done, the aa mutations will be back.

**Comment by MarieLataretu** [comment]
Thanks, @corneliusroemer, I completely agree that we wouldn't have that behavior with a correct fasta input - and biologically spoken it makes sense!

Other tools like `covSonar` report also mutations within a frame shift. If you look at the nucleotide mutations independently, you'd still have the mutations within the frame shift.
