### ISSUE TITLE
Question: Difference between `missing` and `not sequenced` at beginning of sequence

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/nextclade#757]
Looking at sequences with a nucleotide deletion at `520-` ([see here](https://clades.nextstrain.org/?dataset-name=sars-cov-2&input-fasta=https%3A%2F%2Flapis.cov-spectrum.org%2Fopen%2Fv1%2Fsample%2Ffasta%3Fhost%3DHomo%2Bsapiens%26orderBy%3Drandom%26limit%3D200%26dateFrom%3D2021-09-13%26nucMutations%3D518-%26downloadAsFile%3Dtrue)) I noticed a strange inconsistency at how we report missing nucleotides at the beginning of the sequence.

Almost all sequences don't start right at the beginning, that's normal. But here, some seem to state: `missing 1-50` while others say `not sequenced 1-247` etc.

Why do we once say one thing, and at other times the other? I don't quite understand how this can happen.

Here are two examples, different color, different names. But what's the difference?

![image](https://user-images.githubusercontent.com/25161793/159132288-9a014101-eb7a-465e-9b80-77e09d9f5b31.png)

![image](https://user-images.githubusercontent.com/25161793/159132289-f485d48c-c670-4107-9276-2b7725d29b5f.png)

**Comment by ivan-aksamentov** [comment]
@corneliusroemer

"Not sequenced" highlights areas before `alignmentBegin` and after `alignmentEnd`. These correspond to the contiguous gaps that are added during alignment in the beginning and end of the incomplete query sequence in order for it to be aligned with ref sequence. These gaps are treated specially since someone requested this feature. Otherwise they would be just massive deletions.

"Missing" is nucs `N` in the original query sequence. They are shown as is. Gaps are not added during alignment because these areas already align well. Perhaps someone added `N`s as padding. Perhaps these sequences are already aligned.

Like many things in bioinformatics, it seems that there is no agreement on what these areas in the sequences should be. So some people pad with `N`s and other don't. Might be different sequencing techniques. Might be that sequences come to Nextclade already aligned and padded.

Nextclade originally displayed things as they come out of alignment (Nextalign), but then "Not sequenced" feature got added. Perhaps this needs to be clarified in the docs.
