### ISSUE TITLE
[ERROR] Nextclade: semver::version::from_string invalid version.

### ISSUE THREAD

**Issue by tseemann** [nextstrain/nextclade#872]
```
$ conda create -n nc nextclade

$ conda activate nc

$ nextclade --version
1.11.0

$ nextclade dataset list
[ERROR] Nextclade: semver::version::from_string invalid version.
```

**Comment by ivan-aksamentov** [comment]
Hi @tseemann,

Thanks for the report!

Datasets should be fixed and released now: https://github.com/nextstrain/nextclade_data/pull/30, https://github.com/nextstrain/nextclade_data/pull/31

Let me know if it works now.

Context: it was broken due to mistake made during preparation for transition to Nextclade v2 ([changelog](https://github.com/nextstrain/nextclade/blob/master/CHANGELOG.md#nextclade-200)).

Note, that Nextclade v2 will be released on 2022-06-28 12:00 UTC, and Nextclade v1 will no longer be receiving updates after that. So if you are working on a new project, it might make sense to focus on [v2 betas](https://github.com/nextstrain/nextclade/releases) instead. There is a few breaking changes, and the documentation will be updated in the coming days, but the changelog and `--help` should hopefully provide some insight.

**Comment by tseemann** [comment]
Thanks @ivan-aksamentov !

I read the V2 changelog and noticed the cmdline changes.
I look forward to a full V2 release next week.

Thank you for your prompt fix.
