### ISSUE TITLE
Is it by design that sequence with lots of Ns are classified as recombinant?

### ISSUE THREAD

**Issue by danrlu** [nextstrain/nextclade#918]
This sequence has mostly Ns with 1 mutation and is "recombinant". Just checking that this is intended behavior. Certainly a little confusing.  
<img width="788" alt="image" src="https://user-images.githubusercontent.com/20667188/176790614-b69caf68-6ae7-4b04-a027-d464874b0c77.png">

**Comment by corneliusroemer** [comment]
Hi Dan!

A sequence with 28816 Ns is very much a total edge case. How many non-N bases do you even have? It can't be more than a thousand!

In that regime, it's basically impossible to place sequences phylogenetically with any confidence - too little information.

The reason this ends up as a recombinant is that recombinants have stretches from two lineages, so in order to say whether something is a recombinant or not you need non-N bases from either side of the breakpoint. Otherwise it's impossible to be sure and one needs to use some sort of prior (which in this case would be very much against this sequence being a recombinant).

But we don't do any prior weighting - we just traverse the tree and choose the best match - maybe we could bias against assigning a recombinant if there's a non-recombinant that has the same parsimony score.

Otherwise, you could run it through the dataset that has no recombinants:
<img width="846" alt="image" src="https://user-images.githubusercontent.com/25161793/176895252-ae3c4bef-2b4d-4f68-a5cc-f605a6b9cb8d.png">

I hope that helps. There are two potential improvements we can make:
1. Improve the lineage we assign when there are equally parsimonious placements, e.g. bias against recombinants
2. Add a note of the number of equally parsimonious placements to show uncertainty

One question for you: did you notice the high number of Ns? The sequence is colored red so one shouldn't really trust the lineage assignment. Should that be made clearer?

**Comment by danrlu** [comment]
This all makes sense. Very interesting to think through! 

This came up as we were QC-ing the sequence, and usually we would discard anything with so many Ns, but seeing it as recombinant made us think it twice and wondering whether we would miss anything interesting by throwing it away... But as you said the lineage assignment is not meaningful in this case. I remember there are other reasons a sequence would be red, right? Like too many mixed sites, I never ignore sequences b/c they're red. I think for seq w too many Ns, it's best to not show lineage at all. 

I think in general it could be helpful to show confidence in the lineage assignment one way or another, but then the question become whether that will be additionally confusing, and that's a bigger Q than this issue at hand.

Thanks very much for the great tool and always improving it!
