### ISSUE TITLE
Output a row for ALL input sequences

### ISSUE THREAD

**Issue by tseemann** [nextstrain/nextclade#921]
In `nextclade run` 1.x i was guaranteed to get  one output row/record for each input sequence.

But in 2.x some poor quality sequences say this:

```2022-07-04 05:22:58.508 [W] nextclade_ordered_writer.rs:164: In sequence #50677 '20VR3072': Unable to align: low seed matching rate. Details: number of seeds: 299, number of seed matches: 23, matching rate: 0.077, required matching rate: 0.300. Note that this sequence will not be included in the results.```

And the output CSV has no entry for it.

Could you enable the old behaviour with an option please?

**Comment by ivan-aksamentov** [comment]
> In nextclade run 1.x i was guaranteed to get one output row/record for each input sequence.

Can you provide an example for v1 where a failed sequence would be included into results?

Nextclade v1 should also omit the results from CSV/TSV outputs for sequences that don't align or fail otherwise. This behavior is not changed in v2.

There is a separate "errors.csv" file (`--errors-csv`) which contains all the rows, along with errors and warnings.

Or do you have a problem with a particular sequence in v2 but not v1? 

You can try to adjust the minimum required matching rate using argument `--min-match-rate`. It is 0.3 by default (30% of attempted seed matches should succeed). Note that when attempting to align large viruses with low matching rate, it may cause very high memory consumption (up to tens and hundreds of gigabytes) and may lead to OOM-killer shutting down Nextclade process. This option acts as a safeguard. Also with this match rate, the alignment and the analysis results will be gibberish, so there is not much reason to salvage these sequences.

**Comment by ivan-aksamentov** [comment]
@tseemann Disregard my last message. Indeed v1 outputs the results of failed sequences and v2 does not. This was not intended. We discuss with the team on how is better to proceed.

**Comment by ivan-aksamentov** [comment]
Alright, #922 should fix this. There are some more improvements for other formats as well. If all goes well, we will [release](https://github.com/nextstrain/nextclade/releases) a new version on Tuesday, July 12.

**Comment by tseemann** [comment]
@ivan-aksamentov Thanks for your efforts on this request.
I will check the new version on 12 July (13 July for me :-)

**Comment by tseemann** [comment]
I can confirm this is working now - thank you so much @ivan-aksamentov !
