### ISSUE TITLE
Change in SARS-CoV-2 variant aa mutation profile after nextclade update

### ISSUE THREAD

**Issue by seharley** [nextstrain/nextclade#949]
Background: My lab uses Illumina's COVIDSeq platform to sequence SARS-CoV-2 variants, including Illumina's BaseSpace sequencing analysis platform (DRAGEN COVID Lineage application), which utilizes NextClade for viral clade / mutation assessment.  Illumina just updated their DRAGEN COVID Lineage app (to version 3.5.10), which per their tech support utilizes NextClade v2.3.0 (earlier version of Illumina's app used NextClade v1.1.0).  I ran 5 previously analyzed positive samples on the new analysis platform.  One of the samples shows a different number in the NextClade table "totalMissing" column (1801 in original Illumina app v3.5.9 and 1461 in new Illumina app v3.5.10) and reports a number of changes in predicated amino acid substitutions.  

Can you review the results and help me understand what changed in the sequence alignment profiles for the different versions?
Please see the attached excel sheet, which includes the results from Illumina's analysis results (the NextClade result table) for this patient (v3.5.9 / v1.1.0 and v3.5.10 / v2.3.0).

Thank you! - Susan Harley (UAMS, Little Rock, AR)
[COVIDSeq_1015439856_2-data-output-versions_Harley.xlsx](https://github.com/nextstrain/nextclade/files/9214058/COVIDSeq_1015439856_2-data-output-versions_Harley.xlsx)

**Comment by ivan-aksamentov** [comment]
Hi Susan,

We keep developing Nextclade and there's been a lot of changes over more than a year between 1.1.0 and 2.3.0, including new features, bug fixes, and support for new clades. Hard to tell what exactly caused changed outputs. You can browser the changes in software, starting from 1.1.0 and scroll up from there, although it's a very long list:
https://github.com/nextstrain/nextclade/blob/master/CHANGELOG.md#nextclade-web-130-nextclade-cli-110-nextalign-cli-110-2021-06-22

In software, some of the more significant were the completely new alignment algorithm in 2.0.0 and improvements in frame shift detection. So the changes in outputs could be explained by these.

Additionally, there's been many changes to the Nextclade dataset files. In particular, we keep updating the reference tree to provide more accurate clade assignment for the constantly emerging new strains. The dataset changelog is here:
https://github.com/nextstrain/nextclade_data/blob/master/CHANGELOG.md
The changes in the datatset might also change the outputs significantly.

If you need full reproducibility, you would need to use the same version of Nextclade software and the same version of the dataset across your experiments. It is recommended that you rerun all samples with the newest version - it will likely be more accurate and more informative.

In order to understand the changes, the most useful is probably to compare the old and new alignments and translations produced by Nextclade.

If you are comfortable sharing your input sequences, upload them and me and my teammates will take a look.

**Comment by seharley** [comment]
Thank you so much for your fast response and explanation.  I can upload the FASTA file that was analyzed on both platforms.  Let me find it.

...
Susan E. Harley, MD
Assistant Professor
Divisions of Hematopathology and Molecular Genetic Pathology
Section Director, Molecular Diagnostics Laboratory
Winthrop P. Rockefeller Cancer Institute 12-188, Slot #774
University of Arkansas for Medical Sciences
4301 W. Markham St. Little Rock, AR 72205
501.686.8697
________________________________

**Comment by ivan-aksamentov** [comment]
Susan @seharley,

There is a little quirk with the GitHub replies over email - I will not be able to see the attachments. Please use the "view it on GitHub" link to return to GitHub website and reply there.

Also note that this thread is public on GitHub, so don't share anything you are not comfortable to share publicly.

**Comment by seharley** [comment]
Here are the combined FASTA file from our original run (date/time 07202022_020655) and the combined FASTA with the 5 of these randomly chosen to be repeated on the newer analysis platform (later date/time 07272022_023043).  The sample we identified output discrepancies in is: **1015439894_7-20-2022**
[COVIDSeq_072022_analysis_DRAGEN-COVID-Lineage_07202022_020655.txt](https://github.com/nextstrain/nextclade/files/9215000/COVIDSeq_072022_analysis_DRAGEN-COVID-Lineage_07202022_020655.txt)
[COVIDSeq_072022_analysis_DRAGEN-COVID-Lineage_07272022_023043.txt](https://github.com/nextstrain/nextclade/files/9215004/COVIDSeq_072022_analysis_DRAGEN-COVID-Lineage_07272022_023043.txt)

**Comment by seharley** [comment]
Just saw your added message -- We upload our sequences (FASTQ) into GenBank, so technically they are public already.  Thank you for the notification.

**Comment by seharley** [comment]
Let me know if it would be more helpful to look at the FASTQ.  I don't automatically download that on my end, so I'd need to grab them from BaseSpace.

**Comment by rneher** [comment]
Hi Susan,

as far as I can tell, the only differences are the number of amino acid substitutions called for `1015439894_7-20-2022`. The old version didn't call `E:T9I`, likely because much of the gene is not covered. The new version is can align smaller fragments of genes and thus is able to call this gene. In the output Ivan produced and shared with me, this sequence is missing 1801 nucleotides in both versions (the excel sheet you shared at the top seems to compare two difference sequences)

![image](https://user-images.githubusercontent.com/8379168/181751177-4c925655-ed40-4f25-9e72-0fe073cddc2e.png)

I hope this helps! let us know if there are additional oddities -- these reports are critical for improving nextclade, so thanks a lot!

**Comment by seharley** [comment]
Good grief, I must have pulled the wrong sample.  Thank you so much for pointing that out!  I really appreciate your time.  Very sorry for my confusion!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
